Squash me: broken update to dev dependencies
I get the following errors. I think they are all from updating TypeScript.

```
ℹ ｢atl｣: Using typescript@3.0.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from /home/olie/projects/tridactyl/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
Error: /home/olie/projects/tridactyl/src/.excmds_content.generated.ts(1497)
 Property 'fullscreenElement' does not exist on type 'Document'.
Error: /home/olie/projects/tridactyl/src/.excmds_content.generated.ts(1643)
 Expected 1 arguments, but got 0.
Error: /home/olie/projects/tridactyl/src/commandline_frame.ts(85)
 Expected 1 arguments, but got 0.
Error: /home/olie/projects/tridactyl/src/commandline_frame.ts(88)
 Expected 1 arguments, but got 0.
Error: /home/olie/projects/tridactyl/src/content/commandline_content.ts(84)
 Expected 1 arguments, but got 0.
Error: /home/olie/projects/tridactyl/src/excmds.ts(1929)
 Property 'fullscreenElement' does not exist on type 'Document'.
Error: /home/olie/projects/tridactyl/src/excmds.ts(2102)
 Expected 1 arguments, but got 0.
Error: /home/olie/projects/tridactyl/src/lib/dom.ts(469)
 Expected 1 arguments, but got 0.
ℹ ｢atl｣: Time: 1099ms
Warning: Unknown language: "text"
Warning: Unknown language: "text"
Rendering [========================================] 100%
```